version: "2"
services:
  db:
    image: mongo:3.4
    volumes:
      - mongo-data:/data/db
  api:
    build: ./api
    environment:
      MONGO_URL: mongodb://db:27017/movies
      NODE_ENV: development
    links:
      - db
    volumes:
      - ./api:/usr/src/app
    ports:
      - "8888:8888"
    entrypoint: npm run watch
volumes:
  mongo-data:
