version: "2"
services:
  db:
    image: mongo:3.4
    volumes:
      - mongo-data:/data/db
  api:
    build: ./api
    environment:
      MONGO_URL: mongodb://db:27017/movies
    links:
      - db
  webserver:
    build: ./webserver
    links:
      - api
volumes:
  mongo-data:
