apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: movie-app-deployment
spec:
  template:
    metadata:
      labels:
        app: movie-app-web
    spec:
      containers:
      - name: app
        image: kenobi883/movie-app:latest
        ports:
        - containerPort: 80
        env:
        - name: API_URL
          value: http://movie-api-service:8888
